services:
  # конфигурация по умолчанию в *этом* файле
  _defaults:
    autowire: true
    autoconfigure: true
    public: true

  Prokl\ServiceProvider\ServiceProvider: ~

  # Прямой алиас сервис-контейнера Symfony. @service_container - deprecated.
  Psr\Container\ContainerInterface: '@service_container'

  # Ядро
  Symfony\Component\HttpKernel\KernelInterface: '@kernel'
  Symfony\Component\HttpKernel\Kernel: '@kernel'

  # Параметры приложения.
  parameter_bag:
    class: Symfony\Component\DependencyInjection\ParameterBag\ContainerBag
    arguments: ["@service_container"]

  # Параметры приложения. Алиас.
  Symfony\Component\DependencyInjection\ParameterBag\ContainerBagInterface: '@parameter_bag'
  Symfony\Component\DependencyInjection\ParameterBag\ParameterBagInterface: '@parameter_bag'

  # Запрос
  app.request:
    class: Prokl\ServiceProvider\Services\AppRequest
    tags: ['service.bootstrap']

  Prokl\ServiceProvider\Services\AppRequest: '@app.request'
  request: '@app.request'

  # Битриксовый Request
  bitrix.request.instance:
    class: Bitrix\Main\HttpRequest
    factory: ['@app.request', 'bitrixRequest']

  # Конвертор битриксового Request в симфонический.
  bitrix.request.convertor:
    public: false
    class: Prokl\ServiceProvider\Services\PSR\BitrixRequestConvertor
    arguments: ['@bitrix.request.instance']

  # Request, импортированный из Битриксового
  bitrix.request:
    class: Symfony\Component\HttpFoundation\Request
    factory: ['@bitrix.request.convertor', 'request']

  # Битриксовый Response
  bitrix.response.instance:
    class: Bitrix\Main\HttpResponse
    factory: ['@app.request', 'bitrixResponse']

  # Конвертор битриксового Response в симфонический.
  bitrix.response.convertor:
    public: false
    class: Prokl\ServiceProvider\Services\PSR\BitrixResponseConvertor
    arguments: ['@bitrix.response.instance']

  # Response, импортированный из Битриксового
  bitrix.response:
    class: Symfony\Component\HttpFoundation\Response
    factory: ['@bitrix.response.convertor', 'response']


  # Request приложения.
  global.request:
    class: Symfony\Component\HttpFoundation\Request
    factory: ['@app.request', 'getRequest']

  # Текущий URL.
  app.request.uri:
    class: Prokl\ServiceProvider\Services\AppRequest
    factory: ['@app.request', 'getRequestUri']
