services:
  # конфигурация по умолчанию в *этом* файле
  _defaults:
    autowire: true
    autoconfigure: true
    public: true

  Prokl\ServiceProvider\ServiceProvider: ~

  # Прямой алиас сервис-контейнера Symfony. @service_container - deprecated.
  Psr\Container\ContainerInterface: '@service_container'

  # Ядро
  Symfony\Component\HttpKernel\KernelInterface: '@kernel'
  Symfony\Component\HttpKernel\Kernel: '@kernel'

  event_dispatcher:
    class: Symfony\Component\EventDispatcher\EventDispatcher

  Symfony\Component\EventDispatcher\EventDispatcher: '@event_dispatcher'
  Symfony\Contracts\EventDispatcher\EventDispatcherInterface: '@event_dispatcher'

  # Параметры приложения.
  parameter_bag:
    class: Symfony\Component\DependencyInjection\ParameterBag\ContainerBag
    arguments: ["@service_container"]

  # Параметры приложения. Алиас.
  Symfony\Component\DependencyInjection\ParameterBag\ContainerBagInterface: '@parameter_bag'
  Symfony\Component\DependencyInjection\ParameterBag\ParameterBagInterface: '@parameter_bag'

  # Запрос
  app.request:
    class: Prokl\ServiceProvider\Services\AppRequest
    tags: ['service.bootstrap']

  Prokl\ServiceProvider\Services\AppRequest: '@app.request'
  request: '@app.request'

  # Манипуляции с делегированными контейнерами.
  delegated_container_manipulator:
    public: true
    class: Prokl\ServiceProvider\Utils\DelegatedContainer\Manipulator
    arguments: [!tagged delegated.container]

  # Битриксовый Request
  bitrix.request.instance:
    class: Bitrix\Main\HttpRequest
    factory: ['@app.request', 'bitrixRequest']

  # Конвертор битриксового Request в симфонический.
  bitrix.request.convertor:
    public: false
    class: Prokl\ServiceProvider\Services\PSR\BitrixRequestConvertor
    arguments: ['@bitrix.request.instance']

  # Битриксовый Request, приведенный к PSR-7
  bitrix.request.psr7:
    class: Prokl\ServiceProvider\Services\PSR\PSR7\PsrRequest
    factory: ['@bitrix.request.convertor', 'psrRequest']

  # Request, импортированный из Битриксового
  bitrix.request:
    class: Symfony\Component\HttpFoundation\Request
    factory: ['@bitrix.request.convertor', 'request']

  # Битриксовый Response
  bitrix.response.instance:
    class: Bitrix\Main\HttpResponse
    factory: ['@app.request', 'bitrixResponse']

  # Конвертор битриксового Response в симфонический.
  bitrix.response.convertor:
    public: false
    class: Prokl\ServiceProvider\Services\PSR\BitrixResponseConvertor
    arguments: ['@bitrix.response.instance']

  # Битриксовый Response, приведенный к PSR-7
  bitrix.response.psr7:
    class: Prokl\ServiceProvider\Services\PSR\PSR7\PsrResponse
    factory: ['@bitrix.response.convertor', 'psrResponse']

  # Response, импортированный из Битриксового
  bitrix.response:
    class: Symfony\Component\HttpFoundation\Response
    factory: ['@bitrix.response.convertor', 'response']

  # Http factory стандарта PSR-17
  psr17.http_factory:
    class: Prokl\ServiceProvider\Services\PSR\PSR17\HttpFactory

  Prokl\ServiceProvider\Services\PSR\PSR17\HttpFactory: '@psr17.http_factory'

  # Http client стандарта PSR-18
  psr18.http_client:
    class: Prokl\ServiceProvider\Services\PSR\PSR18\PsrClient

  Prokl\ServiceProvider\Services\PSR\PSR18\PsrClient: '@psr18.http_client'

  # Request приложения.
  global.request:
    class: Symfony\Component\HttpFoundation\Request
    factory: ['@app.request', 'getRequest']

  # Текущий URL.
  app.request.uri:
    class: Prokl\ServiceProvider\Services\AppRequest
    factory: ['@app.request', 'getRequestUri']


  controller_resolver:
    class: Symfony\Bundle\FrameworkBundle\Controller\ControllerResolver
    arguments: ['@service_container']

  Symfony\Bundle\FrameworkBundle\Controller\ControllerResolver: '@controller_resolver'

  argument_metadata_factory:
    class: Symfony\Component\HttpKernel\ControllerMetadata\ArgumentMetadataFactory

  Symfony\Component\HttpKernel\ControllerMetadata\ArgumentMetadataFactory: '@argument_metadata_factory'

  argument_resolver:
    class: Symfony\Component\HttpKernel\Controller\ArgumentResolver
    arguments:
      - '@argument_metadata_factory'
      - [
        '@argument_resolver.request_attribute',
        '@argument_resolver.session',
        '@argument_resolver.service',
        '@argument_resolver.default',
        '@argument_resolver.variadic',
      ]

  Symfony\Component\HttpKernel\Controller\ArgumentResolver: '@argument_resolver'

  argument_resolver.request_attribute:
    class: Symfony\Component\HttpKernel\Controller\ArgumentResolver\RequestAttributeValueResolver
    tags:
      - {name: controller.argument_value_resolver, priority: 100}

  Symfony\Component\HttpKernel\Controller\ArgumentResolver\RequestAttributeValueResolver: '@argument_resolver.request_attribute'

  argument_resolver.request:
    class: Symfony\Component\HttpKernel\Controller\ArgumentResolver\RequestValueResolver
    tags:
      - {name: controller.argument_value_resolver, priority: 50}

  Symfony\Component\HttpKernel\Controller\ArgumentResolver\RequestValueResolver: '@argument_resolver.request'

  argument_resolver.session:
    class: Symfony\Component\HttpKernel\Controller\ArgumentResolver\SessionValueResolver
    tags:
      - {name: controller.argument_value_resolver, priority: 50}

  Symfony\Component\HttpKernel\Controller\ArgumentResolver\SessionValueResolver: '@argument_resolver.session'

  argument_resolver.service:
    class: Symfony\Component\HttpKernel\Controller\ArgumentResolver\ServiceValueResolver
    tags:
      - {name: controller.argument_value_resolver, priority: 50}

  Symfony\Component\HttpKernel\Controller\ArgumentResolver\ServiceValueResolver: '@argument_resolver.service'

  argument_resolver.default:
    class: Symfony\Component\HttpKernel\Controller\ArgumentResolver\DefaultValueResolver
    tags:
      - {name: controller.argument_value_resolver, priority: -150}

  Symfony\Component\HttpKernel\Controller\ArgumentResolver\DefaultValueResolver: '@argument_resolver.default'

  argument_resolver.variadic:
    class: Symfony\Component\HttpKernel\Controller\ArgumentResolver\VariadicValueResolver
    tags:
      - {name: controller.argument_value_resolver, priority: -150}

  Symfony\Component\HttpKernel\Controller\ArgumentResolver\VariadicValueResolver: '@argument_resolver.variadic'
